### ISSUE TITLE
Retrieve rights for FAHClient for Android.

### ISSUE THREAD

**Issue by ProDigit** [sonyxperiadev/Folding-home#4]
(Kindly) ask Sony to donate the rights for the Android client for FAH.
This with further development of the client version for future folding in mind; mainly using ARM based chips, (with or without GPUs).

While currently ARM GPUs are slow, 48 core versions already hit the market.
I think it would be a shame that all work would be abandoned, especially if in the future, ARM based servers running multiple GPUs, could be the future for deep learning and folding super-computers.

**Comment by ewkoob** [comment]
Any work on this being done?  Would be nice to have a working client during the pandemic.

**Comment by jzoran** [comment]
This project is licensed under MIT license and there are 12 forks including the fork by Folding@Home project. We would love to see a working Android client, but unfortunately don't have allocated resources for continued maintenance. We have open sourced the project some 3 years ago with hope that the thriving Folding@Home community can reuse the code to the benefit of all.
